// Builds and executes the HTTP request with the browser's native fetch().
// No proxy, no backend — CORS rules of the browser apply.

import { statusTextFor, detectBodyKind } from './format.js';

export const METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'];
export const METHODS_WITH_BODY = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);

/** Normalize the URL: must be absolute http(s). Throws {kind:'invalid-url'}. */
export function normalizeUrl(raw) {
  const trimmed = String(raw || '').trim();
  if (!trimmed) throw { kind: 'invalid-url' };
  let parsed;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw { kind: 'invalid-url' };
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw { kind: 'invalid-url' };
  }
  return parsed;
}

function enabledRows(rows) {
  return (rows || []).filter((r) => r.enabled && String(r.key || '').trim() !== '');
}

/** Build the effective URL + headers + body exactly as they will be sent. */
export function buildFetchInput(req) {
  const url = normalizeUrl(req.url);
  url.search = '';
  for (const p of enabledRows(req.params)) {
    url.searchParams.append(p.key, p.value ?? '');
  }

  const headers = [];
  for (const h of enabledRows(req.headers)) {
    headers.push([h.key.trim(), h.value ?? '']);
  }

  // Auth
  const auth = req.auth || { type: 'none' };
  if (auth.type === 'bearer' && auth.bearer) {
    headers.push(['Authorization', `Bearer ${auth.bearer}`]);
  } else if (auth.type === 'basic') {
    const creds = `${auth.basicUser || ''}:${auth.basicPass || ''}`;
    headers.push(['Authorization', `Basic ${btoa(creds)}`]);
  } else if (auth.type === 'apikey' && auth.apiKey) {
    const name = (auth.apiKeyName || 'X-API-Key').trim() || 'X-API-Key';
    if ((auth.apiKeyIn || 'header') === 'header') headers.push([name, auth.apiKey]);
    else url.searchParams.append(name, auth.apiKey);
  }

  // Body
  let body = undefined;
  let bodyText = null;
  const wantsBody = METHODS_WITH_BODY.has(req.method);
  const bodyType = req.body?.type || 'none';
  if (wantsBody && bodyType !== 'none') {
    const hasContentType = headers.some(([k]) => k.toLowerCase() === 'content-type');
    if (bodyType === 'json') {
      const raw = req.body.json || '';
      try {
        if (raw.trim()) JSON.parse(raw);
      } catch (e) {
        throw { kind: 'invalid-json', detail: e.message };
      }
      body = raw;
      bodyText = raw;
      if (!hasContentType) headers.push(['Content-Type', 'application/json']);
    } else if (bodyType === 'text') {
      body = req.body.text || '';
      bodyText = body;
      if (!hasContentType) headers.push(['Content-Type', 'text/plain']);
    } else if (bodyType === 'urlencoded') {
      const sp = new URLSearchParams();
      for (const r of enabledRows(req.body.urlencoded)) sp.append(r.key, r.value ?? '');
      body = sp.toString();
      bodyText = body;
      if (!hasContentType) headers.push(['Content-Type', 'application/x-www-form-urlencoded']);
    } else if (bodyType === 'form') {
      const fd = new FormData();
      for (const r of enabledRows(req.body.form)) fd.append(r.key, r.value ?? '');
      body = fd;
      bodyText = null; // multipart boundary is generated by the browser
    }
  }

  return { url: url.toString(), headers, body, bodyText };
}

function headersToObject(headers) {
  const out = {};
  headers.forEach((value, key) => {
    const k = key.toLowerCase();
    out[k] = out[k] ? `${out[k]}, ${value}` : value;
  });
  return out;
}

/**
 * Execute the request. Resolves with a response record, or throws a
 * classified error: invalid-url | invalid-json | timeout | cancelled |
 * cors | network | dns.
 */
export async function executeRequest(req, signal) {
  const input = buildFetchInput(req);
  const started = performance.now();
  let res;
  try {
    res = await fetch(input.url, {
      method: req.method,
      headers: input.headers,
      body: input.body,
      signal,
      redirect: 'follow',
    });
  } catch (e) {
    if (e?.name === 'AbortError') {
      throw signal?.aborted && signal?.reason === 'timeout'
        ? { kind: 'timeout' }
        : { kind: 'cancelled' };
    }
    if (e instanceof TypeError) {
      // Browsers hide the real cause; the overwhelmingly common one for
      // fetch() TypeErrors on absolute URLs is CORS or unreachable host.
      throw { kind: 'cors', detail: e.message };
    }
    throw { kind: 'network', detail: e?.message };
  }

  const duration = performance.now() - started;
  const buf = await res.arrayBuffer();
  const size = buf.byteLength;
  let bodyText = '';
  try {
    bodyText = new TextDecoder('utf-8', { fatal: false }).decode(buf);
  } catch {
    bodyText = '';
  }
  const headersObj = headersToObject(res.headers);
  const contentType = headersObj['content-type'] || '';
  const kind = detectBodyKind(contentType, bodyText);

  return {
    status: res.status,
    statusText: statusTextFor(res.status, res.statusText),
    duration: Math.round(duration),
    size,
    headers: headersObj,
    body: bodyText,
    contentType,
    kind,
  };
}
